---
title: "R Notebook"
output: html_notebook
---

```{r,echo=FALSE, warning=FALSE,results='hide',message=FALSE}
source("../aux.R")
data <- read_delim("../data/inform_mun.csv", delim = "|")
estructura <- read_yaml("../data/estructura_indice.yaml")
```


# Limpieza Categóricas 

```{r,warning=FALSE,message=FALSE}
###############
# Categóricas -> Numéricas
# Clasifica las categóricas por tipo
# Como ya están categorizadas las volvemos numéricas

categoricas_5 <- get_var_from_type(estructura,"categorica_5")
data[,categoricas_5]  <- data[,categoricas_5] %>% 
  mutate_all(funs(recode(var = ., 
                         recodes = "'Muy bajo'=0;
                         'Bajo'=25;
                         'Medio'=50;'Alto'=75;
                         'Muy alto'=100")))

#Existencia de unidad de protección civil
#{0-NA|1-si|2-no|3-en proceso de integracion|8-info no disponible|9-no se sabe}
categoricas_nd_spnn1 <- get_var_from_type(estructura,"categoricas_nd_spnn1")
data[,categoricas_nd_spnn1]  <- data[,categoricas_nd_spnn1] %>% 
  mutate_all(funs(recode(var = ., 
                         recodes = "0=0;
                         1=0;2=100;
                         3=25;8=50;
                         9=50")))

#Existencia de Atlas de Riesgo
#Participacion ciudadana
#{0-NA|1-si|2-no|8-info no disponible|9-no se sabe}
categoricas_nd_nsnn1y4 <- get_var_from_type(estructura,"categoricas_nd_nsnn1y4")
data[,categoricas_nd_nsnn1y4]  <- data[,categoricas_nd_nsnn1y4] %>% 
  mutate_all(funs(recode(var = ., 
                         recodes = "0=0;
                         1=0;2=100;
                         8=50;9=50")))

# Cobro predial
# {0-NA|1-gobierno municipal|2-gobierno de la Entidad Federativa|3-No se cobra|9-No se sabe}
categoricas_aut_cobr <- get_var_from_type(estructura,"categoricas_aut_cobr")
data[,categoricas_aut_cobr]  <- data[,categoricas_aut_cobr] %>% 
  mutate_all(funs(recode(var = ., 
                         recodes = "0=0;
                         1=0;2=25;
                         8=100;9=50")))

#Info publica disponible

#Mecanismos de transparencia
data <- data %>% 
  mutate(mec_tran = ifelse(mec_tran!=0,100,0))
```

# Limpieza Numéricas

```{r,echo=FALSE, warning=FALSE,results='hide',message=FALSE, include=FALSE}
###############
# Numéricas
# Define las variables numéricas (Obtener de yaml)
numericas <- get_var_from_type(estructura,"^numerica$")
data[,numericas] <- lapply(data[, numericas], as.numeric) 

# Queremos que inform siempre sea más es peor
# Acá define las variables donde más sea mejor
mas_mejor <- get_var_from_type(estructura,"^mas_mejor$")
data[,mas_mejor] <- data[,mas_mejor]*-1  

# Crear cortes
# kmeans (por ahora)
lapply(numericas, get_cuts, data=data)
```


# Análisis de Correlación

```{r}
amenazas <- get_var_from_name(estructura, "Amenazas")
vulnerabilidad <- get_var_from_name(estructura, "Vulnerabilidad")
capacidades <- get_var_from_name(estructura, "Capacidades")
data <- to_numeric(data, amenazas) 
data <- to_numeric(data, vulnerabilidad)
data <- to_numeric(data, capacidades) 

res <- data %>% select(amenazas) %>% drop_na()
corrplot(cor(res), type = "upper",  
         tl.col = "black", tl.srt = 45)
res <- data %>% select(capacidades) %>% drop_na()
corrplot(cor(res), type = "upper",  
         tl.col = "black", tl.srt = 45)
res <- data %>% select(vulnerabilidad) %>% drop_na()
corrplot(cor(res), type = "upper", 
         tl.col = "black", tl.srt = 45)


```


# Agregado de Dimensión
TODO - función
```{r}
# TODO() - recursive function
# Try other aggregate functions
dimensiones <- names(estructura$Inform$Dimensión)

for (dimension in dimensiones) {
  subdimensiones <- estructura$Inform$Dimensión[[eval(dimension)]] %>% 
    purrr::flatten() %>% names()
  for (subdimension in subdimensiones) {
    Subsubdimensiones <- estructura$Inform$Dimensión[[
      eval(dimension)]]$Subdimensión[[eval(subdimension)]] %>% 
     purrr::flatten() %>% names()
    for (Subsubdimensión in Subsubdimensiones) {
      variables <- get_var_from_name(estructura,Subsubdimensión)
      data[Subsubdimensión] <- data[variables] %>% as.data.frame() %>% 
        rowMeans(na.rm = TRUE)
  }
  data[subdimension] <- data[Subsubdimensiones] %>% as.data.frame() %>% 
    rowMeans(na.rm = TRUE)
}
data[dimension] <- data[subdimensiones] %>% as.data.frame() %>% 
  rowMeans(na.rm = TRUE)
}

data["INFORM"] <-apply(data[dimensiones], 1,geometric.mean,na.rm=TRUE)
```


```{r}
options(scipen=999)
tmp <- data %>% 
  dplyr::select(INFORM, dimensiones) %>% 
  gather() 
tmp %>% ggplot(aes(value)) + 
  theme_fivethirtyeight(base_size = 20) +
  facet_wrap( ~ key) +
  geom_histogram(bins = 25) + 
  theme(axis.title = element_text()) + 
  ylab('Observaciones') + 
  xlab("Calificación")  

```

```{r}
res <- data %>% 
  dplyr::select(INFORM, dimensiones)
corrplot(cor(res), type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}
data("df_mxmunicipio")
df_mxmunicipio <- df_mxmunicipio %>% left_join(data, by = c("region"="cve_muni"))

plot_map(df_mxmunicipio, "INFORM", "Reds")
plot_map(df_mxmunicipio, "1. Amenazas y Exposición", "Oranges")
plot_map(df_mxmunicipio, "2. Falta de Capacidades de Respuesta", "Greens")
plot_map(df_mxmunicipio, "3. Vulnerabilidad", "PuBu")
```



```{r}
declaratoria <-dbrsocial::load_table(con,raw,declaratoria) %>% 
  dbrsocial::retrieve_result()

declaratoria_muni <-  declaratoria %>%
  mutate(anio = as.integer(str_extract(fecha_inicio, "^[0-9]{4}"))) %>%
  filter(anio==2016) %>%
  dplyr::mutate(cve_muni = str_pad(clave_completa, 5, pad = "0")) %>%
  group_by(cve_muni) %>% summarise(declaratorias_n = n()) %>%
  mutate(declaratorias_n = declaratorias_n)

res <- data %>% 
  dplyr::select(cve_muni, INFORM, dimensiones)
temp <- res %>% 
  left_join(declaratoria_muni, by="cve_muni") %>% 
  select(INFORM, dimensiones, declaratorias_n)

cor(temp %>% drop_na())

```

```{r}
ggplot(data = temp) + 
  geom_point(mapping = aes(x = declaratorias_n, y = INFORM)) +
  geom_smooth(mapping = aes(x = declaratorias_n, y = INFORM), method=lm) 
```

