---
title: "estados_matrix_creation"
output: html_document
---

```{r setup, include=FALSE}
options(scipen=10000)
source("../utils.R")
```
## TODO 
* La ingesta de inpc está mal, sólo toma 32 de las 46 ciudades. 
* Moni iba a agregar la enigh

###########################################################################
AMENAZAS
###########################################################################

```{r, results = "hide"}
# INPC
inpc <- large_table(con,raw,inpc_estados) %>% 
  filter(fecha == "2016-9") %>% 
  select(-fecha)

# Sistema de alertas: liquidez y endeudamiento
s_alertas <- large_table(con,raw,sistemas_alertas) %>% 
  mutate(endeudamiento = (indicador1+indicador2+indicador3)/3,liquidez = 
           ingresosdelibredisposicion/(pi+pi_2+obligacionesacortoplazoyproveedoresycontratistas),
         nom_ent=entidadfederativa) %>% select(-entidadfederativa)
s_alertas$nom_ent <- str_replace_all(s_alertas$nom_ent, c("Ciudad de México" = "Distrito Federal","Coahuila" = "Coahuila de Zaragoza","Veracruz" = "Veracruz de Ignacio de la Llave","Michoacán" = "Michoacán de Ocampo"))
cves <- large_table(con, raw,geom_estados) %>% 
  select(cve_ent,nom_ent)
sistema_alertas <- left_join(cves, s_alertas, by = "nom_ent") %>% 
  select(cve_ent,endeudamiento,liquidez)

# Join
amenazas_edo <- left_join(inpc, sistema_alertas, by = "cve_ent") %>% retrieve_result()
  
# Generación de Reporte
amenazas_numericas_edo <- na.omit(scale(select_if(amenazas_edo, is.numeric)))

# Generación de Reporte
create_reports(amenazas_numericas_edo %>% data.table(), 
               task_name = "amenazas_edo", 
               output_dir = "../eda/reportes/amenazas") 
```

###########################################################################
CAPACIDADES
###########################################################################

```{r, results = "hide"}
# Selección y Construcción de Variables

cves <- large_table(con, raw,geom_estados) %>% 
  select(cve_ent,nom_ent)
# Jueces y agentes fiscales por cada cien mil habitantes
jueces <- large_table(con, raw, inegi_jueces) %>%
  mutate(nom_ent=entidadfederativa) %>%
  select(nom_ent,num_jueces) 
jueces$nom_ent <- str_replace_all(jueces$nom_ent, c("Ciudad de México" = "Distrito Federal","Ciudad de México" = "Distrito Federal"))
inegi_jueces <- left_join(cves, jueces, by = "nom_ent") %>% select(-nom_ent) %>%
  retrieve_result()

agentes_fiscales <- large_table(con, raw, inegi_agentes_fiscales) %>%
  rename(nom_ent=entidad_federativa) %>%
  select(nom_ent,num_agentes_fiscales) 
agentes_fiscales$nom_ent <- str_replace_all(agentes_fiscales$nom_ent, c("Ciudad de México" = "Distrito Federal","Ciudad de México" = "Distrito Federal"))
inegi_agentes_fiscales <- left_join(cves, agentes_fiscales, by = "nom_ent") %>% select(-nom_ent) %>%
  retrieve_result()

# Índice de sistema político estable y funcional
periodistas <- large_table(con,raw,imco_periodistas) %>% 
  rename(nom_ent=entidad_federativa) %>%
  select(-c(data_date,actualizacion_sedesol)) 
equidad_congreso <- large_table(con,raw,imco_equidad_congreso) %>% 
  rename(nom_ent=entidad_federativa) %>%
  select(-c(data_date,actualizacion_sedesol)) 
corrupcion_estatal <- large_table(con,raw,imco_corrupcion_estatal) %>% 
  rename(nom_ent=entidad_federativa) %>%
  select(-c(data_date,actualizacion_sedesol))
partidos <- large_table(con,raw,imco_corrupcion_partidos) %>% 
  select(-c(entidadfederativa,data_date,actualizacion_sedesol)) %>% retrieve_result()
corrupcion_partidos <- data.frame(nom_ent=c("Aguascalientes","Baja California","Baja California Sur","Campeche","Coahuila de Zaragoza","Colima","Chiapas","Chihuahua","Distrito Federal","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","México","Michoacán de Ocampo","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro de Arteaga","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz de Ignacio de la Llave","Yucatán","Zacatecas"),partidos)
matrimonio_igualitario <- large_table(con,raw,imco_matrimonio_igualitario) %>% 
  rename(nom_ent=estado) %>% 
  select(-c(data_date,actualizacion_sedesol))
info <- large_table(con,raw,imco_info_publica) %>%
  mutate(cve_ent=as.character(entidad)) %>%
  select(-c(data_date,actualizacion_sedesol,entidad)) %>% distinct()
info_publica <- left_join(cves,info,by='cve_ent')
participacion_ciudadana <- large_table(con,raw,imco_participacion_ciudadana) %>%
  rename(nom_ent=entidad) %>% 
  select(-c(data_date,actualizacion_sedesol)) 
corrupcion_sector <- large_table(con,raw,imco_corrupcion_sector)

indice_sist_politico <- left_join(corrupcion_estatal,equidad_congreso, by='nom_ent') %>% 
  left_join(periodistas,by='nom_ent') %>%
  left_join(matrimonio_igualitario,by='nom_ent') %>%
  left_join(info_publica,by='nom_ent') %>%
  left_join(corrupcion_sector,by='nom_ent') %>%
  left_join(participacion_ciudadana,by='nom_ent') %>% retrieve_result() %>%
  left_join(corrupcion_partidos,by='nom_ent')

# Join
capacidades_edo <- left_join(inegi_jueces, inegi_agentes_fiscales, by="cve_ent") %>% 
  left_join(indice_sist_politico, by="cve_ent")

# Generación de Reporte
create_reports(capacidades_edo, 
               task_name = "capacidades_edo", 
               output_dir = "../eda/reportes/capacidades")
```

###########################################################################
VULNERABILIDADES
###########################################################################
```{r, results = "hide"}
#ENIGH
concentrados <-large_table(con, clean, enigh_concentrados) %>% 
  select(folioviv, foliohog, ubica_geo, factor_hog) %>% retrieve_result()

poblacion <-large_table(con, clean, enigh_poblacion) %>% 
  select(folioviv, foliohog, numren, sexo, edad, disc1, disc2, disc3, disc4, disc5, disc6, disc7, hor_4, min_4, usotiempo4) %>% retrieve_result()

trabajos <-large_table(con, clean, enigh_trabajos) %>% 
  select(folioviv, foliohog, numren, pres_12) %>% retrieve_result()

ingresos <- large_table(con, clean, enigh_ingresos) %>% 
  select(folioviv, foliohog, numren, clave, ing_tri) %>% retrieve_result()

enigh1 <- full_join(poblacion, trabajos)
enigh1_1 <- full_join(enigh1, ingresos)
enigh2 <- full_join(enigh1_1,concentrados)

enigh2$factor_hog <- as.integer(enigh2$factor_hog)

enigh <- mutate(enigh2, cve_muni = substr(enigh2$ubica_geo, 1, 5))

##Ojo que aquí me falta sacar la población total de cada municipio con el factor

##Discapacidad intelectual

enigh_disc_int <- enigh[ which( enigh$disc1 == 6 | enigh$disc2 == 6 | enigh$disc3 == 6 | enigh$disc4 == 6 | enigh$disc5 == 6 | enigh$disc6 == 6 | enigh$disc7 == 6) , ]  

##Usar el factor de expansión para contar cuantas personas tienen la discapacidad de tipo 6 y hacer exactamente lo mismo para las personas que tienen las demás discapacidades.

##Prestación de guarderías

enigh_guarderías <- enigh %>% 
  filter(pres_12 == 12)

##Tiempo a trabajo no remunerado 

enigh_trabajonr <- enigh %>% 
  mutate(tiempo1 = hor_4*60) %>% 
  mutate(tiempo2 = tiempo1 + min_4) %>% 
  mutate(tiempo_tnr = tiempo2/60)

##Brecha salarial

enigh_brecha <- enigh %>% 
  filter(clave == p001 & p011)
```